version: '3'

services:
  api:
    container_name: api_emprestimos
    env_file:
      - .env
    build: .
    command: npm run start:dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
    networks:
      - api_emprestimos

  database:
    image: postgres:13
    volumes:
      - './.postgres-data/db:/var/lib/postgresql/data'
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - api_emprestimos

networks:
  api_emprestimos:
    driver: bridge
